### ISSUE TITLE
MAIN BACKEND ISSUE WITH TRANSACTIONS

### ISSUE THREAD

**Issue by SirGian99** [pedalami/pedalami#32]
Transactions seem not to work properly. For example, sometimes one can join two times the same team because even if you receive 200 as a response, the transaction does not save the user in the team. Hence, the second join can be done. This is a HUGE problem since all the transactional approach must be revisited.

**Comment by Sbi98** [comment]
Check with branch txV2

**Comment by Sbi98** [comment]
Solved
