### ISSUE TITLE
App crashing 

### ISSUE THREAD

**Issue by MaxGio98** [pedalami/pedalami#7]
When you sign out from the app and you sign in back again the app crashes. Seems that crashes when it tries to load the map. Error: 

java.lang.NullPointerException: Attempt to invoke interface method 'void org.osmdroid.api.IMapController.stopAnimation(boolean)' on a null object reference

**Comment by MaxGio98** [comment]
Same for each page that is not the map page

**Comment by Sbi98** [comment]
Solved in new map branch
